// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"基本的なパラメーターを設定するプラグインです。","parameters":{"cacheLimit":"20","screenWidth":"1024","screenHeight":"768","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"on"}},
{"name":"CustomizeConfigDefault","status":true,"description":"オプションデフォルト値設定プラグイン","parameters":{"常時ダッシュ":"ON","コマンド記憶":"OFF","BGM音量":"20","BGS音量":"20","ME音量":"20","SE音量":"20","常時ダッシュ消去":"OFF","コマンド記憶消去":"ON","BGM音量消去":"OFF","BGS音量消去":"OFF","ME音量消去":"OFF","SE音量消去":"OFF"}},
{"name":"HalfMove","status":true,"description":"半歩移動プラグイン","parameters":{"8方向移動":"true","8方向移動スイッチ":"0","イベントすり抜け":"true","強制中無効":"true","角回避":"true","斜め移動中減速":"false","トリガー拡大":"false","実歩数調整":"false","上半分移動不可地形":"[\"0\"]","上半分移動不可Region":"[\"0\"]","下半分移動不可地形":"[\"0\"]","下半分移動不可Region":"[\"0\"]","右半分移動不可地形":"[\"0\"]","右半分移動不可Region":"[\"0\"]","左半分移動不可地形":"[\"0\"]","左半分移動不可Region":"[\"0\"]","右上移動不可地形":"[\"0\"]","右上移動不可Region":"[\"0\"]","右下移動不可地形":"[\"0\"]","右下移動不可Region":"[\"0\"]","左上移動不可地形":"[\"0\"]","左上移動不可Region":"[\"0\"]","左下移動不可地形":"[\"0\"]","左下移動不可Region":"[\"0\"]","全方向移動不可地形":"[\"0\"]","全方向移動不可Region":"[\"0\"]","イベント複数起動防止":"false","イベント位置重複OK":"false"}},
{"name":"SecondaryCategories","status":true,"description":"ver1.02/アイテムにセカンダリカテゴリを設定できようにします。","parameters":{"UseSubItemCategory":"false","AllIncludesCategory":"すべて"}},
{"name":"CategorySynthesis","status":true,"description":"ver1.00/添加道具合成功能。【需要SecondaryCategories】","parameters":{"DefaultSynthesisName":"合成","DefaultSynthesisCategories":"道具,武器,防具,贵重品","NeedMachineryName":"必要器材","NeedMaterialName":"必要素材","MaterialListText":"材料","SynthesisText":"制作","NumberSynthesisText":"制作_num个","SynthesisHelp":"按上下键选择数量。","EstimateText":"完成品","SynthesisPriceText":"合成费用","ChangeRecipeTone":"206,68,24,0","SynthesisResultText":"完成品","SynthesisSeName":"Item1","SynthesisSeSettings":"90,100,0","MenuSynthesisCommandName":""}},
{"name":"FixImageLoading","status":true,"description":"画像ロード時のチラつき防止プラグイン","parameters":{}},
{"name":"DynamicDatabase","status":true,"description":"動的データベース構築プラグイン","parameters":{}},
{"name":"GraphicalDesignMode","status":true,"description":"GUI画面デザインプラグイン\nパラメータを変更したら「プロジェクトの保存」（Ctrl+S）","parameters":{"デザインモード":"false","自動保存":"false","モバイル版作成":"false","モバイル偽装":"false","ウィンドウ透過":"false","グリッドサイズ":"48","パディング":"0","フォントサイズ":"0","行の高さ":"0","背景透明度":"0","アイコンサイズ調整":"false","背景表示可否固定":"false","右クリックで消去":"false"}},
{"name":"DisableFastForward","status":true,"description":"イベント高速化禁止プラグイン","parameters":{}},
{"name":"MessageWindowHidden","status":true,"description":"メッセージウィンドウ一時消去プラグイン","parameters":{"triggerButton":"[\"shift\"]","triggerSwitch":"0","linkPictureNumbers":"","linkShowPictureNumbers":"[]","disableLinkSwitchId":"0","disableSwitchId":"0","disableInBattle":"false","disableInChoice":"true"}},
{"name":"PictureVariableSetting","status":true,"description":"ピクチャ関連のイベント機能拡張プラグイン","parameters":{"初期値":"OFF","ピクチャ表示最大数":""}},
{"name":"DTextPicture","status":true,"description":"動的文字列ピクチャ生成プラグイン","parameters":{}},
{"name":"FixChoiceListWindowY","status":true,"description":"選択肢ウィンドウのY座標固定パッチ","parameters":{"y":"512"}},
{"name":"TMNamePop","status":true,"description":"イベントの頭上に文字列を表示する機能を追加します。","parameters":{"backOpacity":"96","fontSize":"17","outlineWidth":"4","outlineColor":"rgba(0, 0, 0, 0.5)","width":"160","roundRectRadius":"6"}},
{"name":"TMBalloonLoop","status":true,"description":"フキダシアイコンをループ表示させます。","parameters":{}},
{"name":"TMEventItemEx","status":true,"description":"アイテム選択の処理にヘルプウィンドウを追加し、\n個数表示の有無と表示行数をアイテムタイプごとに設定できます。","parameters":{"helpWindowEnabledItem":"1","helpWindowEnabledKey":"1","helpWindowEnabledA":"1","helpWindowEnabledB":"1","showItemNumberItem":"1","showItemNumberKey":"1","showItemNumberA":"1","showItemNumberB":"1","numVisibleRowsItem":"4","numVisibleRowsKey":"4","numVisibleRowsA":"4","numVisibleRowsB":"4","fixPlacement":"bottom"}},
{"name":"TMItemCategoryEx","status":true,"description":"添加、删除道具分类。","parameters":{"categoryList":"道具 礼物 生物 服装 贵重品"}},
{"name":"MPP_ChoiceEX","status":true,"description":"【ver.3.7】選択肢の機能拡張","parameters":{"maxPageRow":"6","=== Command ===":"","Plugin Commands":"{\"ChoicePos\":\"ChoicePos\",\"ChoiceVariableId\":\"ChoiceVariableId\",\"ChoiceRect\":\"ChoiceRect\"}","Event Comment":"{\"ChoiceHelp\":\"選択肢ヘルプ\"}"}},
{"name":"SupponShopStock","status":true,"description":"设置拥有库存系统的商店。version 1.04m1","parameters":{"Label of stock Number":"库存数","Label of sold out":"已售罄","Display option":"false","Display option space":"12"}},
{"name":"nonStopCharacter","status":true,"description":"画面外に出たマップイベントの動きを停止しないようにするプラグインです。","parameters":{}},
{"name":"MKR_PlayerMoveForbid","status":true,"description":"(v1.0.5) プレイヤー移動禁止プラグイン","parameters":{"Default_Move_Flag":"10","Default_Menu_Flag":"true","Enter Flag":"true"}},
{"name":"MKR_ControlCharacterEx","status":true,"description":"(v1.2.1) 制御文字拡張プラグイン","parameters":{"Default_SE_Volume":"90","Default_SE_Pitch":"100","Default_SE_Pan":"0","Default_ME_Volume":"90","Default_ME_Pitch":"100","Default_ME_Pan":"0","Default_Wait_Period":"15","Default_Wait_Line":"60","Default_Name_Color":"0","Default_Icon_Margin":"0","Default_Gold_Background":"0","Default_Gold_Position":"6","Message_Icon_Margin":"4"}}
];
